global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_oracle'
    static_configs:
      - targets: ['oracle-db:9100']
  - job_name: 'node_mysql'
    static_configs:
      - targets: ['mysql-db:9100']
  - job_name: 'oracle_db'
    static_configs:
      - targets: ['oracledb_exporter:9161']
  - job_name: 'mysql_db'
    static_configs:
      - targets: ['mysqld_exporter:9104']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']