apiVersion: 1

deleteDatasources: []

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
    uid: prometheus

  - name: MySQL
    type: mysql
    url: mysql-db:3306
    database: mysql
    user: ${MYSQL_GRAFANA_USER}
    editable: true
    secureJsonData:
      password: ${MYSQL_GRAFANA_PASSWORD}
    uid: mysql-datasource
    jsonData:
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
